# Section 4.2 Expected value of a continuous random variable

If a random variable has a continuous distribution for which the p.d.f. is $f$, then the expectation $E(X)$ is defined as


### Example: Jail time
Suppose $X$ is the random variable that represents the prison sentence in years for persons convicted of grand theft auto and assume that $X$ has a p.d.f. of $f(x)=\frac{1}{9}x^{2}$ for $0<x<3$. What is the **average** length of time these people spend in jail? Calculate this by hand, and using R. 

\vspace{3cm}

### You try it
Find the expected value for the following p.d.f.; $f(x)=2x$ for $0<x<1$.

\vspace{5cm}

\newpage

As in the discrete case, we can also define functions of random variables. 

## Theorem 4.2

Let $X$ be a continuous random variable and let $g$ be a function.
$$
E[g(X)]=\int g(x)f(x)dx
$$

### Example
Let $Y$ have probability density function $f_{Y}(y)=2(1-y), 0\leq y\leq 1$.  Suppose that $W=Y^{2}$, in which case
\[
f_{W}(w)=\frac{1}{\sqrt{w}}-1,0\leq w\leq1
\]
Find $E(W)$ a) using $f(w)$ directly, and b) using theorem 4.2. Confirm both using R. 



\newpage
### Example
Suppose that the p.d.f. of a random variable $X$ with a continuous distribution is $f(x)=2x$ for $0<x<1$. Find the expectation of $1/X$. Do this by hand, confirming your results using R. 

\vspace{5cm}
### You try it
Grades on the last test were not very good. Their distribution is as follows:
$$
f(y)=\frac{1}{5000}(100-y) \qquad \mbox{ for } 0\leq y\leq 100
$$
As a way of curving the results, the professor announces that he will replace each person's grade, $Y$, with a new grade $g(Y)$ where $g(Y)=10\sqrt{Y}$. Will the professor's strategy be successful in raising the class average above 60? Write down the equation, then use R to calculate the value. 
 
\newpage
Additional notes.
